name: Trigger Jenkins

on:
  push:
    branches:
      - main

jobs:
  send_to_jenkins:
    runs-on: self-hosted

    steps:
      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            http://localhost:8080/job/webhooktest1/build
