name: Trigger Jenkins

on:
  push:
    branches:
      - main

jobs:
  send_to_jenkins:
    runs-on: self-hosted

    steps:
      - name: checking networking 
        run: |
          ping -c 5 localhost
          nslookup localhost
          traceroute localhost
      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST \
            -u Jenkins:119035841c4f3428de2eb663230530ddc1 \
            -H "Content-Type: application/json" \
                http://localhost:8080/job/webhooktest1/build
