name: Trigger Jenkins

on:
  push:
    branches:
      - main

jobs:
  send_to_jenkins:
    runs-on: self-hosted

    steps:
      - name: checking networking 
        run: |
          nslookup localhost \
          && echo "Command 1 executed successfully" \
          && echo "Another command executed here" \
          && echo "hihi"
      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST \
            -u Jenkins:119035841c4f3428de2eb663230530ddc1 \
            -H "Content-Type: application/json" \
            --data '{ "parameter": [{"name": "CHOICE", "value": "one"}]}' \
                http://localhost:8080/job/webhooktest1/buildWithParameters
